org: niklasnilsson
app: exam-app
service: exam-app

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::376129862797:role/LambdaDynamoDBuserRole

functions:
  getKey:
    handler: functions/getKey/index.getRandomKey
    events:
      - httpApi:
          path: /key
          method: get

  regUser:
    handler: functions/regUser/index.regUser
    events:
      - httpApi:
          path: /register/{key}
          method: post

  getUser:
    handler: functions/getUser/index.getUser
    events:
      - httpApi:
          path: /get/user/{id}
          method: get

  loginUser:
    handler: functions/loginUser/index.loginUser
    events:
      - httpApi:
          path: /login/user
          method: post

  removeFriend:
    handler: functions/removeFriend/index.removeFriend
    events:
      - httpApi:
          path: /remove/friend
          method: post
  addFriend:
    handler: functions/addFriend/index.addFriend
    events:
      - httpApi:
          path: /add/friend
          method: post
  deleteUser:
    handler: functions/deleteUser/index.deleteUser
    events:
      - httpApi:
          path: /delete/user/{id}
          method: delete

package:
  patterns:
    - node_modules/dotenv/**
    - validations/**
    - utils/**
    - functions/getUser/**
    - functions/loginUser/**
    - services/**
    - models/**
    - responses/**
    - data/**

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LunaChat-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: nickname
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: nickname-index
            KeySchema:
              - AttributeName: nickname
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
