org: niklasnilsson
app: exam-app
service: exam-app

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::376129862797:role/LambdaDynamoDBuserRole

functions:
  getKey:
    handler: functions/getKey/index.getRandomKey
    events:
      - httpApi:
          path: /key
          method: get

  regUser:
    handler: functions/regUser/index.regUser
    events:
      - httpApi:
          path: /register/{key}
          method: post

package:
  patterns:
    - node_modules/dotenv/**
    - validations/**
    - utils/**
    - functions/**
    - services/**
    - models/**
    - responses/**
    - data/**

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LunaChat-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST